apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-7
    app.kubernetes.io/part-of: rh-trex-7
  name: rh-trex-7prte
spec:
  path: /
  port:
    targetPort: 8000
  to:
    kind: Service
    name: rh-trex-7
    weight: null
status: {}
